### ISSUE TITLE
Get userName to appear with posts on feed

### ISSUE THREAD

**Issue by relspeedwagon** [100devs-socialnetwork/socialnetwork-main#31]
post.user is displayed currently but value of ".user" references DB id

**Comment by Memphis1983** [comment]
@relspeedwagon Correct! I tried that too. We need to reference the `User `model into the `Post `model and make use of the `populate `method to grab the username to our `db.posts` collection, we must also add this extra parameter `postedBy: user` into our Post Schema and do the same in /createPost route, So that property gets added to every post which then links to our `Post.ejs` 😪
